### ISSUE TITLE
App craches on executing call or answer - Issue with native library jingle_peerconnection_so

### ISSUE THREAD

**Issue by eldarj** [flutter-webrtc/dart-sip-ua#191]
Android app crashes when executing a call or answer.

Using sip_ua 0.3.5

Registering works all fine, and everything seems ok, but the app crashes with given error when executing a call.

```
I/org.webrtc.Logging(  399): NativeLibrary: Loading native library: jingle_peerconnection_so
I/org.webrtc.Logging(  399): NativeLibrary: Loading library: jingle_peerconnection_so
E/org.webrtc.Logging(  399): NativeLibrary: Failed to load native library: jingle_peerconnection_so
E/org.webrtc.Logging(  399): NativeLibrary: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.app-Y8JckI2kba0skxUOF3XFfw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.app-Y8JckI2kba0skxUOF3XFfw==/lib/arm64, /data/app/com.example.app-Y8JckI2kba0skxUOF3XFfw==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libjingle_peerconnection_so.so"
E/org.webrtc.Logging(  399): NativeLibrary: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.app-Y8JckI2kba0skxUOF3XFfw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.app-Y8JckI2kba0skxUOF3XFfw==/lib/arm64, /data/app/com.example.app-Y8JckI2kba0skxUOF3XFfw==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libjingle_peerconnection_so.so"
E/org.webrtc.Logging(  399): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
E/org.webrtc.Logging(  399): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/org.webrtc.Logging(  399): 	at java.lang.System.loadLibrary(System.java:1667)
E/org.webrtc.Logging(  399): 	at org.webrtc.NativeLibrary$DefaultLoader.load(NativeLibrary.java:21)
E/org.webrtc.Logging(  399): 	at org.webrtc.NativeLibrary.initialize(NativeLibrary.java:44)
E/org.webrtc.Logging(  399): 	at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:294)
E/org.webrtc.Logging(  399): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.ensureInitialized(MethodCallHandlerImpl.java:139)
E/org.webrtc.Logging(  399): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:167)
E/org.webrtc.Logging(  399): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/org.webrtc.Logging(  399): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/org.webrtc.Logging(  399): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
E/org.webrtc.Logging(  399): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/org.webrtc.Logging(  399): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/org.webrtc.Logging(  399): 	at android.os.Looper.loop(Looper.java:197)
E/org.webrtc.Logging(  399): 	at android.app.ActivityThread.main(ActivityThread.java:7814)
E/org.webrtc.Logging(  399): 	at java.lang.reflect.Method.invoke(Native Method)
E/org.webrtc.Logging(  399): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/org.webrtc.Logging(  399): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/ing.flutterpin(  399): No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
E/AndroidRuntime(  399): FATAL EXCEPTION: main
E/AndroidRuntime(  399): Process: com.example.app, PID: 399
E/AndroidRuntime(  399): java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
E/AndroidRuntime(  399): 	at org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals(Native Method)
E/AndroidRuntime(  399): 	at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:295)
E/AndroidRuntime(  399): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.ensureInitialized(MethodCallHandlerImpl.java:139)
E/AndroidRuntime(  399): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:167)
E/AndroidRuntime(  399): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(  399): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(  399): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
E/AndroidRuntime(  399): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(  399): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime(  399): 	at android.os.Looper.loop(Looper.java:197)
E/AndroidRuntime(  399): 	at android.app.ActivityThread.main(ActivityThread.java:7814)
E/AndroidRuntime(  399): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(  399): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(  399): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Lost connection to device.
```

**Comment by hard1k9850** [comment]
Were you able to solve the problem?
