### ISSUE TITLE
Crash: Uknown native RtpTransceiverDirection type4

### ISSUE THREAD

**Issue by eugenioadapta** [flutter-webrtc/dart-sip-ua#245]
Using Asterisk server on FreePBX on Android with example app
Register into the Account page (OK)
Call a mobile number
As soon as the mobile answers the call, the app crashes

```
W/System.err(23887): java.lang.IllegalArgumentException: Uknown native RtpTransceiverDirection type4
W/System.err(23887): 	at org.webrtc.RtpTransceiver$RtpTransceiverDirection.fromNativeIndex(RtpTransceiver.java:61)
W/System.err(23887): 	at org.webrtc.RtpTransceiver.nativeDirection(Native Method)
W/System.err(23887): 	at org.webrtc.RtpTransceiver.getDirection(RtpTransceiver.java:182)
W/System.err(23887): 	at com.cloudwebrtc.webrtc.PeerConnectionObserver.transceiverToMap(PeerConnectionObserver.java:890)
W/System.err(23887): 	at com.cloudwebrtc.webrtc.PeerConnectionObserver.onAddTrack(PeerConnectionObserver.java:448)
E/rtc     (23887): #
E/rtc     (23887): # Fatal error in: gen/sdk/android/generated_metrics_jni/../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 94
E/rtc     (23887): # last system error: 0
E/rtc     (23887): # Check failed: !env->ExceptionCheck()
E/rtc     (23887): # 
F/libc    (23887): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 24079 (signaling_threa), pid 23887 (example.example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86_arm:11/RSR1.201013.001/6903271:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2021-11-19 08:43:33+0100
pid: 23887, tid: 24079, name: signaling_threa  >>> com.example.example <<<
uid: 10188
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
    eax 00000000  ebx 00005d4f  ecx 00005e0f  edx 00000006
    edi e972281e  esi a75facc0
    ebp ebe58b90  esp a75fac68  eip ebe58b99
```

```
backtrace:
      #00 pc 00000b99  [vdso] (__kernel_vsyscall+9)
      #01 pc 0005ad68  /apex/com.android.runtime/lib/bionic/libc.so (syscall+40) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
      #02 pc 00076511  /apex/com.android.runtime/lib/bionic/libc.so (abort+209) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
      #03 pc 00435cd9  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #04 pc 00435c71  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #05 pc 0041b804  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #06 pc 0088f1c0  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #07 pc 0088e89a  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (Java_org_webrtc_RtpTransceiver_nativeDirection+53) (BuildId: 764ab8967184581c)
      #08 pc 00142132  /apex/com.android.art/lib/libart.so (art_quick_generic_jni_trampoline+82) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #09 pc 0013baf2  /apex/com.android.art/lib/libart.so (art_quick_invoke_static_stub+418) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #10 pc 001d0392  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+258) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #11 pc 00386701  /apex/com.android.art/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+385) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #12 pc 0037aa3e  /apex/com.android.art/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1070) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #13 pc 007a4d2d  /apex/com.android.art/lib/libart.so (MterpInvokeStatic+637) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #14 pc 00135921  /apex/com.android.art/lib/libart.so (mterp_op_invoke_static+33) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #15 pc 0028aa5a  [anon:dalvik-classes.dex extracted in memory from /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/base.apk] (org.webrtc.RtpTransceiver.getDirection+10)
      #16 pc 007a14fe  /apex/com.android.art/lib/libart.so (MterpInvokeVirtual+1806) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #17 pc 001357a1  /apex/com.android.art/lib/libart.so (mterp_op_invoke_virtual+33) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #18 pc 0000f43e  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/base.apk!classes3.dex] (com.cloudwebrtc.webrtc.PeerConnectionObserver.transceiverToMap+62)
      #19 pc 007a14fe  /apex/com.android.art/lib/libart.so (MterpInvokeVirtual+1806) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #20 pc 001357a1  /apex/com.android.art/lib/libart.so (mterp_op_invoke_virtual+33) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #21 pc 00010548  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/base.apk!classes3.dex] (com.cloudwebrtc.webrtc.PeerConnectionObserver.onAddTrack+516)
      #22 pc 0036fb02  /apex/com.android.art/lib/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.16375758241455872412)+370) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #23 pc 00379b00  /apex/com.android.art/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+176) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #24 pc 0078b325  /apex/com.android.art/lib/libart.so (artQuickToInterpreterBridge+1061) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #25 pc 0014220d  /apex/com.android.art/lib/libart.so (art_quick_to_interpreter_bridge+77) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #26 pc 0013b922  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub+338) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #27 pc 001d0381  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+241) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #28 pc 0062f81c  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, char*)+620) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #29 pc 0062fa35  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, char*)+85) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #30 pc 004a5871  /apex/com.android.art/lib/libart.so (art::JNI<true>::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, char*)+753) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #31 pc 003f85c2  /apex/com.android.art/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, char*, art::Primitive::Type, art::InvokeType)+1586) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #32 pc 003e3e99  /apex/com.android.art/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, char*)+73) (BuildId: 8191579dfafff37a5cbca70f9a73020f)
      #33 pc 0041b8bd  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #34 pc 008864a3  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #35 pc 009ab950  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #36 pc 009afa7f  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #37 pc 009b8bb4  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #38 pc 009aaaa3  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #39 pc 00987816  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #40 pc 0099937b  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #41 pc 00999326  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #42 pc 009992bc  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #43 pc 00468912  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #44 pc 00468059  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #45 pc 00467167  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #46 pc 00468571  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #47 pc 004684b0  /data/app/~~dYMAbCVlz6BQ4tYYfNqJHw==/com.example.example-8NvCjSFyubwYVpgOu8HkuQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 764ab8967184581c)
      #48 pc 000e6974  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+100) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
      #49 pc 00078567  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+71) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
```

The Asterisk server shows 

```
[2021-11-19 08:43:35] VERBOSE[25091][C-00000013] res_rtp_asterisk.c: Got RTP packet from 5.144.89.39:42944 (type 08, seq 000284, ts 3166531308, len 000160)	
2811	[2021-11-19 08:43:35] VERBOSE[25090][C-00000013] res_rtp_asterisk.c: Sent RTP packet to 94.124.59.191:53925 (type 00, seq 022799, ts 3166531304, len 000160)	
2812	[2021-11-19 08:43:35] ERROR[24983] res_http_websocket.c: Error reading from web socket: Success	
2813	[2021-11-19 08:43:35] VERBOSE[2100] res_pjsip_registrar.c: Removed contact 'sip:qjpvk59n@94.124.59.191:51050;transport=ws' from AOR '2003' due to shutdown	
2814	[2021-11-19 08:43:35] VERBOSE[13210] res_pjsip/pjsip_options.c: Contact 2003/sip:qjpvk59n@94.124.59.191:51050;transport=ws has been deleted	
2815	[2021-11-19 08:43:35] VERBOSE[13210] res_pjsip/pjsip_configuration.c: Endpoint 2003 is now Unreachable	
2816	[2021-11-19 08:43:35] VERBOSE[21339] res_http_websocket.c: WebSocket connection from '94.124.59.191:51050' closed	
```

**Expected behavior**
The call should not crash the app

** Notes **
The same app on Web Chrome doesn't have this error (but it's actually muted)
The app works fine using 
https://github.com/flutter-webrtc/dockers/tree/main/asterisk
Flutter Doctor shows no issues
The rtpTransceiver.java file has no type4! 
https://chromium.googlesource.com/external/webrtc/+/HEAD/sdk/android/api/org/webrtc/RtpTransceiver.java

```
public enum RtpTransceiverDirection {
--
  | SEND_RECV(0),
  | SEND_ONLY(1),
  | RECV_ONLY(2),
  | INACTIVE(3);

```

Any Clue on what is calling this java file?

Thank you

**System Infomation()**
Flutter SDK Version: 2.2.2
Target OS and Version: Android sdk 22-30
Host OS and Version: Asterisk 16

**Comment by 97loser** [comment]
getting same issue

**Comment by eugenioadapta** [comment]
The problem for me was an incorrect server configuration (I cannot say it for sure, but I think that WebRTC was not activated for the extension)
Still it is a bug, because a type4 answer is probably an error type that must be managed as an Exception, and should not crash.

**Comment by MoeidHeidari** [comment]
The same error I have. Please provide a solution :(

**Comment by eugenioadapta** [comment]
Sorry I don't know what caused this, but has to do with Asterisk server configuration. 
I didn't find any way to try/catch the error

**Comment by MoeidHeidari** [comment]
There is no problem with Asterisk because it work on chrome without any problem. It just crashes on Android. Even it works on android android 9 but crashed on android 11.

**Comment by ShahzadUmarBaig** [comment]
```
W/System.err(17652): java.lang.IllegalArgumentException: Uknown native RtpTransceiverDirection type4
W/System.err(17652): 	at org.webrtc.RtpTransceiver$RtpTransceiverDirection.fromNativeIndex(RtpTransceiver.java:61)
W/System.err(17652): 	at org.webrtc.RtpTransceiver.nativeDirection(Native Method)
W/System.err(17652): 	at org.webrtc.RtpTransceiver.getDirection(RtpTransceiver.java:182)
W/System.err(17652): 	at com.cloudwebrtc.webrtc.PeerConnectionObserver.transceiverToMap(PeerConnectionObserver.java:915)
W/System.err(17652): 	at com.cloudwebrtc.webrtc.PeerConnectionObserver.onAddTrack(PeerConnectionObserver.java:452)
E/rtc     (17652): 
E/rtc     (17652): 
E/rtc     (17652): #
E/rtc     (17652): # Fatal error in: gen/sdk/android/generated_metrics_jni/../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 94
E/rtc     (17652): # last system error: 0
E/rtc     (17652): # Check failed: !env->ExceptionCheck()
E/rtc     (17652): # 
F/libc    (17652): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 18248 (signaling_threa), pid 17652 (lus_flutter_app)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'KDDI/SOV39_jp_kdi/SOV39:10/52.1.C.0.360/052001C000036000726438165:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-03-20 21:16:44+0500
pid: 17652, tid: 18248, name: signaling_threa  >>> com.nautilus.nautilus_flutter_app <<<
uid: 10474
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
    x0  0000000000000000  x1  0000000000004748  x2  0000000000000006  x3  0000006efbaa3b90
    x4  fefefefefefefeff  x5  fefefefefefefeff  x6  fefefefefefefeff  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  e9e2f1a6cbf19716  x10 0000000000000001  x11 0000000000000000
    x12 fffffff0fffffbdf  x13 ffffffffffffffff  x14 0000000000000004  x15 ffffffffffffffff
    x16 0000006ff353e8c0  x17 0000006ff351ac80  x18 0000006ee3b5c000  x19 00000000000044f4
    x20 0000000000004748  x21 00000000ffffffff  x22 0000006f10ec306a  x23 0000006f065cc222
    x24 0000000000000008  x25 0000006efbaa6020  x26 0000006f626118b0  x27 0000000000000002
    x28 0000006efbaa3ed0  x29 0000006efbaa3c30
    sp  0000006efbaa3b70  lr  0000006ff34cc52c  pc  0000006ff34cc558
backtrace:
      #00 pc 0000000000083558  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: 4ac85d8f66f3a910f00f4ebf4d6bcd1a)
      #01 pc 0000000000391f90  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #02 pc 0000000000391f28  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #03 pc 0000000000379e88  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #04 pc 0000000000379dac  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #05 pc 00000000006e518c  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #06 pc 00000000006e4898  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (Java_org_webrtc_RtpTransceiver_nativeDirection+48) (BuildId: 2c9b0d636b2e9057)
      #07 pc 0000000000140350  /apex/com.android.runtime/lib64/libart.so (art_quick_generic_jni_trampoline+144) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #08 pc 00000000001375b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #09 pc 000000000014600c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #10 pc 00000000002e3678  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #11 pc 00000000002de8d8  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+892) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #12 pc 00000000005a3708  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+372) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #13 pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #14 pc 000000000020c536  [anon:dalvik-classes8.dex extracted in memory from /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!classes8.dex] (org.webrtc.RtpTransceiver.getDirection+10)
      #15 pc 00000000005a0ef4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1352) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #16 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #17 pc 000000000002ebc6  [anon:dalvik-classes2.dex extracted in memory from /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!classes2.dex] (com.cloudwebrtc.webrtc.PeerConnectionObserver.transceiverToMap+62)
      #18 pc 00000000005a0ef4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1352) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #19 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #20 pc 000000000002fcf8  [anon:dalvik-classes2.dex extracted in memory from /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!classes2.dex] (com.cloudwebrtc.webrtc.PeerConnectionObserver.onAddTrack+516)
      #21 pc 00000000002b498c  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.17460956533834400288+240) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #22 pc 000000000059219c  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1032) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #23 pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #24 pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #25 pc 0000000000145fec  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #26 pc 00000000004b0ba0  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #27 pc 00000000004b1fec  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+424) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #28 pc 0000000000397f8c  /apex/com.android.runtime/lib64/libart.so (art::JNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+628) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #29 pc 000000000036ca24  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, std::__va_list, art::Primitive::Type, art::InvokeType)+2368) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #30 pc 000000000035ad04  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+72) (BuildId: b3ce43562b69f2a77abd7f14a6777b0b)
      #31 pc 0000000000379f78  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #32 pc 00000000006dd090  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #33 pc 00000000007debec  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #34 pc 00000000007e2de4  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #35 pc 00000000007ec1d4  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #36 pc 00000000007dde20  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #37 pc 00000000007bcee4  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #38 pc 00000000007cd948  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #39 pc 00000000007cd8dc  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #40 pc 00000000003bf254  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #41 pc 00000000003be950  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #42 pc 00000000003bda20  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #43 pc 00000000003bee3c  /data/app/com.nautilus.nautilus_flutter_app-ND3_8NsMCsB-9B-Ze3rLlw==/base.apk!libjingle_peerconnection_so.so (offset 0x25c6000) (BuildId: 2c9b0d636b2e9057)
      #44 pc 00000000000e6c10  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 4ac85d8f66f3a910f00f4ebf4d6bcd1a)
      #45 pc 0000000000084ee4  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 4ac85d8f66f3a910f00f4ebf4d6bcd1a)
Lost connection to device.
```

Device OS Version: 10
Flutter SDK: 2.8.0
minSDKVersion: 23
targetSDKVersion: 31
compileSDKVersion: 31

It was working fine some days ago, It just started to show up. The calling was working fine on this same device plus it works when the call is incoming when the call is sent from Android to another device and once it is accepted on the other end, then this exception is thrown with the application crashing.

**Comment by ShahzadUmarBaig** [comment]
I have found a solution to this problem.

```
SIPUAHelper sipUaHelper = SIPUAHelper();

// Some function you have created {
   sipUaHelper.call("type your extension here", voiceonly: true);
}

```

Make sure it is set to voiceonly to true, it is not working on the video part.

**Comment by cloudwebrtc** [comment]
fixed https://github.com/flutter-webrtc/dart-sip-ua/pull/321
