### ISSUE TITLE
Uknown native RtpTransceiverDirection type4

### ISSUE THREAD

**Issue by MoeidHeidari** [flutter-webrtc/dart-sip-ua#261]
**Describe the bug**
Voice cal works without any problem. This error happens on video call on android >9. On android <=9 it works also without any problem. It also works on browser correctly.
based on https://chromium.googlesource.com/external/webrtc/+/HEAD/sdk/android/api/org/webrtc/RtpTransceiver.java
it throws an exception when it doesn't recognize the direction value .

``` java


public enum RtpTransceiverDirection {
   SEND_RECV(0),
   SEND_ONLY(1),
   RECV_ONLY(2),
   INACTIVE(3);
    
   private final int nativeIndex;
    
   private RtpTransceiverDirection(int nativeIndex) {
   this.nativeIndex = nativeIndex;
   }
    
   @CalledByNative("RtpTransceiverDirection")
   int getNativeIndex() {
   return nativeIndex;
   }


@CalledByNative("RtpTransceiverDirection")
  static RtpTransceiverDirection fromNativeIndex(int nativeIndex) {
   for (RtpTransceiverDirection type : RtpTransceiverDirection.values()) {
   if (type.getNativeIndex() == nativeIndex) {
   return type;
   }
  }
  throw new IllegalArgumentException(
  "Uknown native RtpTransceiverDirection type" + nativeIndex);
  }
  }

```

**To Reproduce**
1. Go to 'outgoing video call'
 ```bash 
java.lang.IllegalArgumentException: Uknown native RtpTransceiverDirection type4
W/System.err( 8430): 	at org.webrtc.RtpTransceiver$RtpTransceiverDirection.fromNativeIndex(RtpTransceiver.java:61)
W/System.err( 8430): 	at org.webrtc.RtpTransceiver.nativeDirection(Native Method)
W/System.err( 8430): 	at org.webrtc.RtpTransceiver.getDirection(RtpTransceiver.java:182)
W/System.err( 8430): 	at com.cloudwebrtc.webrtc.PeerConnectionObserver.transceiverToMap(PeerConnectionObserver.java:915)
W/System.err( 8430): 	at com.cloudwebrtc.webrtc.PeerConnectionObserver.onAddTrack(PeerConnectionObserver.java:452)
E/rtc     ( 8430): #
E/rtc     ( 8430): # Fatal error in: gen/sdk/android/generated_metrics_jni/../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 94
E/rtc     ( 8430): # last system error: 0
E/rtc     ( 8430): # Check failed: !env->ExceptionCheck()
E/rtc     ( 8430): #
F/libc    ( 8430): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 8491 (signaling_threa), pid 8430 (_sip_ua_example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Android/sdk_phone_x86/generic_x86:11/RSR1.210210.001.A1/7193139:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2022-02-24 06:15:38-0500
pid: 8430, tid: 8491, name: signaling_threa  >>> com.github.cloudwebrtc.dart_sip_ua_example <<<
uid: 10122
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
    eax 00000000  ebx 000020ee  ecx 0000212b  edx 00000006
    edi e9b0f81e  esi aab78cb0
    ebp ef3deb90  esp aab78c58  eip ef3deb99
backtrace:
      #00 pc 00000b99  [vdso] (__kernel_vsyscall+9)
      #01 pc 0005ad68  /apex/com.android.runtime/lib/bionic/libc.so (syscall+40) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
      #02 pc 00076511  /apex/com.android.runtime/lib/bionic/libc.so (abort+209) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
#03 pc 00441f13  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#04 pc 00441eab  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#05 pc 00428334  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#06 pc 008a35a0  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#07 pc 008a2c7a  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (Java_org_webrtc_RtpTransceiver_nativeDirection+53) (BuildId: 15c23e3c0cc52a43)
      #08 pc 001422b2  /apex/com.android.art/lib/libart.so (art_quick_generic_jni_trampoline+82) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #09 pc 0013bc72  /apex/com.android.art/lib/libart.so (art_quick_invoke_static_stub+418) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #10 pc 001d0512  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+258) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #11 pc 00386881  /apex/com.android.art/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+385) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #12 pc 0037abbe  /apex/com.android.art/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1070) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #13 pc 007a6b8d  /apex/com.android.art/lib/libart.so (MterpInvokeStatic+637) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #14 pc 00135aa1  /apex/com.android.art/lib/libart.so (mterp_op_invoke_static+33) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
#15 pc 00349ca2  [anon:dalvik-classes.dex extracted in memory from /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/base.apk] (org.webrtc.RtpTransceiver.getDirection+10)
      #16 pc 007a335e  /apex/com.android.art/lib/libart.so (MterpInvokeVirtual+1806) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #17 pc 00135921  /apex/com.android.art/lib/libart.so (mterp_op_invoke_virtual+33) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
#18 pc 0001006a  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/base.apk!classes4.dex] (com.cloudwebrtc.webrtc.PeerConnectionObserver.transceiverToMap+62)
      #19 pc 007a335e  /apex/com.android.art/lib/libart.so (MterpInvokeVirtual+1806) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #20 pc 00135921  /apex/com.android.art/lib/libart.so (mterp_op_invoke_virtual+33) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
#21 pc 00011194  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/base.apk!classes4.dex] (com.cloudwebrtc.webrtc.PeerConnectionObserver.onAddTrack+516)
      #22 pc 0036fc82  /apex/com.android.art/lib/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.10914192770458939989)+370) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #23 pc 00379c80  /apex/com.android.art/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+176) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #24 pc 0078d185  /apex/com.android.art/lib/libart.so (artQuickToInterpreterBridge+1061) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #25 pc 0014238d  /apex/com.android.art/lib/libart.so (art_quick_to_interpreter_bridge+77) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #26 pc 0013baa2  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub+338) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #27 pc 001d0501  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+241) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
#28 pc 0063167c  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, char*)+620) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #29 pc 00631895  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, char*)+85) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #30 pc 004a6861  /apex/com.android.art/lib/libart.so (art::JNI<true>::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, char*)+753) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #31 pc 003f8742  /apex/com.android.art/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, char*, art::Primitive::Type, art::InvokeType)+1586) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
      #32 pc 003e4019  /apex/com.android.art/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, char*)+73) (BuildId: bf39832c4acabbc939d5c516b6f1d211)
#33 pc 004283ed  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#34 pc 0089a661  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#35 pc 009c1c0c  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#36 pc 009c5fd9  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#37 pc 009cf75c  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#38 pc 009c0d23  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#39 pc 0099d0b2  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#40 pc 009aed4f  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#41 pc 009aecfa  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#42 pc 009aec90  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#43 pc 004758c2  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#44 pc 00475009  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#45 pc 00474117  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#46 pc 00475521  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
#47 pc 00475460  /data/app/~~wnufu5Rn3gFlD3cfPDVyOw==/com.github.cloudwebrtc.dart_sip_ua_example-FTzAN1eLAfTmRw9XYY9xIQ==/lib/x86/libjingle_peerconnection_so.so (BuildId: 15c23e3c0cc52a43)
      #48 pc 000e6974  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+100) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
      #49 pc 00078567  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+71) (BuildId: 6e3a0180fa6637b68c0d181c343e6806)
Lost connection to device.

```

**Expected behavior**
Expected behavior is to get the video from SIP server and just send audio from android app(not video).

**System Infomation()**
Flutter SDK Version: Flutter 2.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db747aa133 (3 weeks ago) • 2022-02-09 13:57:35 -0600
Engine • revision ab46186b24
Tools • Dart 2.16.1 • DevTools 2.9.2

**Comment by dryize** [comment]
Were you able to sort this out?

**Comment by cloudwebrtc** [comment]
fixed https://github.com/flutter-webrtc/dart-sip-ua/pull/321
