### ISSUE TITLE
Parsing "Bye" disappears and an exception occurs

### ISSUE THREAD

**Issue by a42279395** [flutter-webrtc/dart-sip-ua#318]
**Describe the bug**
In a public network environment, an exception occurs when the Bye sent by the peer end disappears

**Expected behavior**
flutter: [2022-09-02 15:33:13.211] Level.debug websocket_interface.dart:173 ::: Received WebSocket message
flutter: [2022-09-02 15:33:13.219] Level.debug transport.dart:313 ::: received text message:
BYE sip:16505957@4y5xzp1644fi.invalid;transport=wss;ob SIP/2.0
Via: SIP/2.0/WSS 1.190.195.26:39468;rport;branch=z9hG4bK78v8Z687UFpBN
Max-Forwards: 70
From: <sip:18745838198@dev.haoxin.cn:7443>;tag=H6gNy7mDH294Q
To: "342-263" <sip:342-263@dev.haoxin.cn:7443>;tag=99q791981b
Call-ID: qgfcm9b7cbkggldexmc3
CSeq: 56498204 BYE
User-Agent: ddtswitch
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY
Supported: timer, path, replaces
Reason: Q.850;cause=31
Content-Length: 0
flutter: input => SIP/2.0/WSS 1.190.195.26:39468;rport;branch=z9hG4bK78v8Z687UFpBN, rule => Via
flutter: Format exception: Expected ALPHA but found '2'
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: FormatException
#0      Grammar.parse
#1      IncomingMessage.parseHeader
#2      parseHeader
#3      parseMessage
#4      UA.onTransportData
#5      Transport._onData
#6      WebSocketInterface._onMessage
#7      WebSocketInterface.connect.<anonymous closure>
#8      WebSocketImpl.connect.<anonymous closure>
#9      _rootRunUnary (dart:async/zone.dart:1434:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#15     _StreamController._add (dart:async/stream_controller.dart:648:7)
#16     _StreamController.add (dart:async/stream_controller.dart:596:5)
#17     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1144:21)
#18     _rootRunUnary (dart:async/zone.dart:1434:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#25     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:332:23)
#26     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:226:46)
#27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#28     _rootRunUnary (dart:async/zone.dart:1434:47)
#29     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#34     _StreamController._add (dart:async/stream_controller.dart:648:7)
#35     _StreamController.add (dart:async/stream_controller.dart:596:5)
#36     _Socket._onData (dart:io-patch/socket_patch.dart:2314:41)
#37     _rootRunUnary (dart:async/zone.dart:1434:47)
#38     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#43     _StreamController._add (dart:async/stream_controller.dart:648:7)
#44     _StreamController.add (dart:async/stream_controller.dart:596:5)
#45     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1107:19)
#46     _rootRun (dart:async/zone.dart:1418:47)
#47     _CustomZone.run (dart:async/zone.dart:1328:19)
#48     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#49     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#50     _rootRun (dart:async/zone.dart:1426:13)
#51     _CustomZone.run (dart:async/zone.dart:1328:19)
#52     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
#53     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#54     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#55     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
flutter: [2022-09-02 15:33:18.791] Level.debug rtc_session.dart:1150 ::: renegotiate()
flutter: [2022-09-02 15:33:18.811] Level.debug rtc_session.dart:2470 ::: sendReinvite()
flutter: [2022-09-02 15:33:18.815] Level.debug rtc_session.dart:1644 ::: createLocalDescription()
flutter: [2022-09-02 15:33:18.826] Level.debug rtc_session.dart:1732 ::: emit "sdp"
flutter: [2022-09-02 15:33:18.831] Level.debug rtc_session.dart:2541 ::: emit "sdp"
flutter: [2022-09-02 15:33:18.834] Level.debug rtc_session.dart:1249 ::: sendRequest()
flutter: [2022-09-02 15:33:18.837] Level.debug transport.dart:167 ::: send()

**System Infomation()**
Flutter SDK Version:3.0.4
Target OS and Version:0.5.2
Host OS and Version:iOS15.4

**Comment by a42279395** [comment]
After testing, it is found that when IP = 1.190.195.26, parsing error will occur, when IP = 10.190.195.26:39468, everything is normal, how to fix it?

**Comment by cloudwebrtc** [comment]
This may be related to Via resolving the host address but not the port.
https://github.com/flutter-webrtc/dart-sip-ua/blob/master/lib/src/grammar.peg#L1095
